### ISSUE TITLE
deploy PKS using pipeline - error: could not find product with 'id' or 'slug'=pcf-automation

### ISSUE THREAD

**Issue by guillierf** [pivotalservices/concourse-pipeline-samples#16]
I got the following issue when running the pipeline to deploy PKS:

job pcf-pipelines-tarball

checking failed

resource script '/opt/resource/check []' failed: exit status 1

stderr:
2018/06/05 17:29:06 Exiting with error: could not find product with 'id' or 'slug'=pcf-automation

**Comment by lsilvapvt** [comment]
Hi @guillierf , the problem seems to be that you do not have access to the "pcf-automation" project in PivNet, which just uncovered a dependency issue with this sample pipeline for people that does not have such access. We will remove such dependency for this pipeline. Thanks for reporting the issue.

**Comment by guillierf** [comment]
@lsilvapvt thanks!
I used the updated files (pipeline.yml and pks_params.yml) and I am able to move forward now.
