### ISSUE TITLE
Install PKS pipeline fails to stage PKS-1.1.0-rc1 (early access) release on Ops Manager

### ISSUE THREAD

**Issue by goutamtadi1** [pivotalservices/concourse-pipeline-samples#19]
Hi,

We used this [pipeline](https://github.com/pivotalservices/concourse-pipeline-samples/blob/master/pipelines/pcf/pks/install-pks/pipeline.yml) previously to install all GA releases of PKS and was working fine.
We got access to PKS-1.1.0-rc1 early release and tried to install with the same pipeline.yml with updated params.

Upload product to Ops Manager was successful. However when staging the product, we are facing the issue explained below:

```
X-Xss-Protection: 1; mode=block
Archive:  ./pivnet-product/pivotal-container-service-1.1.0-build.283.pivotal
  inflating: metadata/metadata.yml   
	Need exactly one unstaged build for pivotal-container-service version 1.1.0-rc1
[]
```

Is there a way to support this early access stage and install ? 
What can we do as a temporary/permanent measure to solve this?

Thanks,
Goutam Tadi
Greenplum-for-Kubernetes

**Comment by lsilvapvt** [comment]
Hi, this issue is supposed to be fixed in the more recent commits, for example: https://github.com/pivotalservices/concourse-pipeline-samples/commit/c0921d83e8aef1f71dce9cb6652adaeafd02f3fa , so please retry it with the latest updates.
Also, make sure that you use the updated version of pipeline.yml ( https://github.com/pivotalservices/concourse-pipeline-samples/blob/master/pipelines/pcf/pks/install-pks/pipeline.yml ) that uses the `stage-product` task from this repo instead of the original one from `pcf-pipelines`.

**Comment by goutamtadi1** [comment]
@lsilvapvt Hey thanks. My bad. That's cruising well now. Closing this issue.
